### ISSUE TITLE
Option to output .kube/config

### ISSUE THREAD

**Issue by toledompm** [jasondavindev/kubernetes-in-docker#2]
I want to access the cluster from the host machine. In order to do that I had to manually copy the content from `.kube/config` to my own. Is there a better way to do this? And if there Is, can I add it to the documentation?

If there isn't I would be more than happy to create a PR to make this process easier

**Comment by jasondavindev** [comment]
In the bootstrap script has the command to set up the config
```bash
kind export kubeconfig --name my-cluster
```

I'll add a new command to Makefile.
